### ISSUE TITLE
com.xxg.jcatch.mbg包下的文件没有找到

### ISSUE THREAD

**Issue by zoro301** [wucao/JCatch#1]
com.xxg.jcatch.mbg包下的文件没有找到，是需要添加依赖还是博主没有提交呢

**Comment by wucao** [comment]
你好，com.xxg.jcatch.mbg包下代码是通过MyBatis Generator自动生成的，创建好MySQL数据表并且配置好src/main/resources/generatorConfig.xml文件中的数据库配置后，可以运行mvn mybatis-generator:generate命令生成代码。

已更新到README.md

**Comment by wucao** [comment]
现已将mbg下自动生成的代码传到github上
