### ISSUE TITLE
找不到依赖包

### ISSUE THREAD

**Issue by SpringStudent** [wucao/JCatch#2]
![image](https://user-images.githubusercontent.com/14833956/33601862-7b3cb802-d9e8-11e7-8e00-eabe1328e116.png)

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/33602798-69e6fd08-d9eb-11e7-905f-ac5d74e72337.png)

**Comment by SpringStudent** [comment]
![image](https://user-images.githubusercontent.com/14833956/33602798-69e6fd08-d9eb-11e7-905f-ac5d74e72337.png)

**Comment by wucao** [comment]
https://raw.githubusercontent.com/wucao/mybatis-generator-limit-plugin/mvn-repo/com/xxg/mybatis-generator-plugin/1.0.0/mybatis-generator-plugin-1.0.0.jar  这个链接可以直接下载的话，那么你试试配置这个maven仓库

**Comment by wucao** [comment]
这个plugin现在可以删掉
